
services:
  nats-server:
    container_name: nats-server
    image: nats:2.10.20-alpine3.20
    ports:
      - "${NATS_PORT}:8222"

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - "${REDIS_PORT}:6379"

  client-gateway:
    depends_on:
      - nats-server
      - redis
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./client-gateway/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${CLIENT_GATEWAY_PORT}
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000" 
    command: pnpm start:dev


  document-generator-ms:
    depends_on:
      - nats-server
      - redis
    container_name: document-generator
    build:
      context: ./document-generator-ms
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./document-generator-ms/src:/usr/src/app/src
      - ./temp-data:/usr/src/app/temp-data
    env_file:
      "./document-generator-ms/.env"
    # environment:
    #   - NODE_ENV=development
    #   - DATABASE_URL=${DATABASE_URL}
    #   - NATS_SERVERS=${NATS_SERVERS}
    #   - PORT=${DOCUMENT_GENERATOR_PORT}
    #   - API_KEY=${API_KEY}
    #   - INVOICE_QUERY_URL=${INVOICE_QUERY_URL}
    #   - CARBONE_LIBREOFFICE=${CARBONE_LIBREOFFICE}
    ports:
      - "${DOCUMENT_GENERATOR_PORT}:3000" 
    command: pnpm start:dev
    networks:
      - default
      - shared-network

  compression-ms:
    depends_on:
      - nats-server
      - redis
    container_name: compression-ms
    build:
      context: ./compression-ms
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./compression-ms/src:/usr/src/app/src
      - ./temp-data:/usr/src/app/temp-data
    env_file:
      "./compression-ms/.env"
    ports:
      - "${COMPRESION_SERVICE_PORT}:3000" 
    command: pnpm start:dev
    networks:
      - default
  
  create-document:
    depends_on:
      - nats-server
      - redis
    container_name: create-document
    build:
      context: ./create-document
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./create-document/src:/usr/src/app/src
      - ./temp-data:/usr/src/app/temp-data
    env_file:
      "./create-document/.env"
    environment:
      - NODE_OPTIONS=--max-old-space-size=5120
    ports:
      - "${CREATE_DOCUMENT_PORT}:3000" 
    command: pnpm start:dev
    networks:
      - default
      
networks:
  shared-network:
    external: true