
services:
  nats-server:
    container_name: nats-server
    image: nats:2.10.20-alpine3.20
    ports:
      - "${NATS_PORT}:8222"
    command: [
      "--max_payload=50000000"  # Configuración del tamaño máximo de carga útil (50 MB)
    ]

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - "${REDIS_PORT}:6379"

  client-gateway:
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./client-gateway/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${CLIENT_GATEWAY_PORT}
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000" 
    command: pnpm start:dev


  document-generator-ms:
    container_name: document-generator
    build:
      context: ./document-generator-ms
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./document-generator-ms/src:/usr/src/app/src
    env_file:
      "./document-generator-ms/.env"
    # environment:
    #   - NODE_ENV=development
    #   - DATABASE_URL=${DATABASE_URL}
    #   - NATS_SERVERS=${NATS_SERVERS}
    #   - PORT=${DOCUMENT_GENERATOR_PORT}
    #   - API_KEY=${API_KEY}
    #   - INVOICE_QUERY_URL=${INVOICE_QUERY_URL}
    #   - CARBONE_LIBREOFFICE=${CARBONE_LIBREOFFICE}
    ports:
      - "${DOCUMENT_GENERATOR_PORT}:3000" 
    command: pnpm start:dev
    networks:
      - default
      - shared-network

  compression-ms:
    container_name: compression-ms
    build:
      context: ./compression-ms
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./compression-ms/src:/usr/src/app/src
    env_file:
      "./compression-ms/.env"
    ports:
      - "${COMPRESION_SERVICE_PORT}:3000" 
    command: pnpm start:dev
    networks:
      - default

networks:
  shared-network:
    external: true